### ISSUE TITLE
Exception connecting

### ISSUE THREAD

**Issue by retog** [pyrho/node-native-messaging-host#1]
I'm trying to connect to the app example of the Readme.

In the browser console I see:

```
JSON.parse: expected property name or '}' at line 1 column 3 of the JSON data 2 subprocess_common.jsm:493
    readJSON resource://gre/modules/subprocess/subprocess_common.jsm:493
```
And this stderr output from native app:

```
internal/buffer.js:79
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:79:11)
    at Buffer.readUInt32LE (internal/buffer.js:215:5)
    at processData ([...]/node_modules/node-native-messaging-host/index.js:38:42)
```

Any insight would be appreciated.

**Comment by pyrho** [comment]
Hey,

Could you maybe share the extension you're trying to connect with? I may be able to take a look.

I have not looked at this code for a while, but it's working fine in [this module that relies on it](https://github.com/pyrho/alfred-firefoxtabswitch).

Cheers.

**Comment by retog** [comment]
Hi, Thanks for the fast answer!

It was basically the client from https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging and the backend from your readme, unfortunately, I no longer have this code as I've now found another approach.

**Comment by pyrho** [comment]
Oh, then you problem is solved I guess ? (:
